name: C/C++ CI -j50

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: configure
      run: ./configure
    - name: make
      run: make -j50
    - name: make check
      run: make -j50 check
    - name: make distcheck
      run: make -j50 distcheck
